version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: payday
      POSTGRES_PASSWORD: payday
      POSTGRES_DB: payday
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
