version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  ai:
    build: ../services/ai
    command: uvicorn main:app --host 0.0.0.0 --port 5055
    ports: ["5055:5055"]
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ../services/api
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ../apps/web
    ports: ["3000:3000"]
    environment:
      NEXT_PUBLIC_AI_BASE: http://ai:5055
      API_BASE_URL: http://api:8000
    depends_on:
      - api
      - ai
