name: Web CI (Next.js)

on:
  pull_request:
  push:
    branches: [ main, "sprint2/**" ]

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install (lockfile)
        run: npm ci

      - name: Lint (if script exists)
        run: npm run lint || echo "no lint script"

      - name: Build
        run: npm run build
